export const transformScanLogList = (data) => ({
  id: data.id,
  token_id: data.token_id,
  token_hash: data.token_hash || "UNKNOWN",
  school_id: data.school_id,
  school_name: data.school,
  student_id: data.student_id,
  student_name: data.student,
  result: data.result,
  scan_type: data.scan_type,
  scan_purpose: data.scan_purpose,
  ip_address: data.ip_address,
  ip_city: data.ip_city,
  ip_country: data.ip_country,
  ip_region: data.ip_region,
  latitude: data.latitude,
  longitude: data.longitude,
  location_derived: data.location_derived,
  device_hash: data.device_hash,
  user_agent: data.device,
  response_time_ms: data.response_time_ms,
  scanned_at: data.created_at,
  scanned_by: data.scanned_by,
  emergency_dispatched: data.emergency_dispatched,
  dispatched_at: data.dispatched_at,
  dispatched_channels: data.dispatched_channels,
  device_info: data.metadata,
});

export const transformScanLogStats = (data) => ({
  total: data.total,
  success: data.success,
  failed: data.failed,
  rateLimited: data.rateLimited,
  emergency: data.emergency,
  successRate: data.successRate,
  avgResponseTimeMs: data.avgResponseTimeMs,
});

export const transformScanLogFilters = (data) => ({
  schools: data.schools,
  scanResults: data.scanResults,
  scanTypes: data.scanTypes,
  scanPurposes: data.scanPurposes,
});

export const transformScanLogDetail = (data) => ({
  id: data.id,
  token_id: data.token_id,
  token_hash: data.token_hash,
  token_status: data.token_status,
  is_honeypot: data.is_honeypot,
  student: data.student,
  student_id: data.student_id,
  school: data.school,
  scan_type: data.scan_type,
  scan_purpose: data.scan_purpose,
  result: data.result,
  ip_address: data.ip_address,
  ip_city: data.ip_city,
  ip_country: data.ip_country,
  ip_region: data.ip_region,
  latitude: data.latitude,
  longitude: data.longitude,
  location_derived: data.location_derived,
  device_hash: data.device_hash,
  user_agent: data.user_agent,
  response_time_ms: data.response_time_ms,
  created_at: data.created_at,
  scanned_at: data.scanned_at,
  scanned_by: data.scanned_by,
  emergency_dispatched: data.emergency_dispatched,
  dispatched_at: data.dispatched_at,
  dispatched_channels: data.dispatched_channels,
  failed_channels: data.failed_channels,
  ip_capture_basis: data.ip_capture_basis,
});
